version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_H2_CONSOLE_ENABLED: "true"
  h2:
    image: oscarfonts/h2
    ports:
      - "8082:8082"
    environment:
      H2_OPTIONS: "-ifNotExists"
